name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  retags:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Retags
        uses: ./
        with:
          component: frontend
          img_build: ${{ github.event.number }}
          img_fallback: test
          repository: bcgov/nr-quickstart-typescript
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ('frontend/')
  # # These build triggers won't match/fire, so images will be retagged
  # name: Retags
  #   uses: ./
  #   strategy:
  #     matrix:
  #       component: [backend, frontend]
  #       include:
  #         - component: backend
  #           triggers: ('backend/')
  #         - component: frontend
  #           triggers: ('frontend/')
  #   secrets:
  #     gh_token: ${{ secrets.GITHUB_TOKEN }}
  #   with:
  #     component: ${{ matrix.component }}
  #     img_build: ${{ github.event.number }}
  #     img_fallback: test
  #     repository: bcgov/nr-quickstart-typescript
  #     triggers: ${{ matrix.triggers }}

  # builds:
  #   # These builds don't have triggers and will fire every time
  #   name: Builds
  #   needs:
  #     - builds-retag
  #   uses: ./
  #   strategy:
  #     matrix:
  #       component: [backend, database, frontend]
  #   secrets:
  #     gh_token: ${{ secrets.GITHUB_TOKEN }}
  #   with:
  #     component: ${{ matrix.component }}
  #     img_build: ${{ github.event.number }}
  #     img_fallback: test
  #     repository: bcgov/nr-quickstart-typescript
