name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # retags:
  #   permissions:
  #     packages: write
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       package: [backend, database, frontend]
  #       include:
  #         - package: backend
  #           triggers: ('backend/')
  #         - package: database
  #           triggers: ('database/')
  #         - package: frontend
  #           triggers: ('frontend/')
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Test Retags
  #       uses: ./
  #       with:
  #         package: ${{ matrix.package }}
  #         tag: ${{ github.event.number }}
  #         tag_fallback: test
  #         repository: bcgov/nr-quickstart-typescript
  #         token: ${{ secrets.GITHUB_TOKEN }}

  # builds:
  #   permissions:
  #     packages: write
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       package: [backend, database, frontend]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Test Builds
  #       uses: ./
  #       with:
  #         package: ${{ matrix.package }}
  #         build_context: ${{ matrix.build_file }}
  #         build_file: ${{ matrix.build_file }}
  #         tag: ${{ github.event.number }}
  #         repository: bcgov/nr-quickstart-typescript
  #         token: ${{ secrets.GITHUB_TOKEN }}

  fom:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [fom-admin, fom-api, db, fom-public]
        include:
          - package: fom-admin
            build_context: .
            build_file: admin/Dockerfile
            triggers: ('admin/')
          - package: fom-api
            build_context: .
            build_file: api/Dockerfile
            triggers: ('api/')
          - package: db
            triggers: ('db/')
          - package: fom-public
            build_context: .
            build_file: public/Dockerfile
            triggers: ('public/')
    steps:
      - uses: actions/checkout@v3
      - name: Test Builds
        uses: ./
        with:
          package: ${{ matrix.package }}
          build_context: ${{ matrix.build_context }}
          build_file: ${{ matrix.build_file }}
          repository: bcgov/nr-fom
          tag: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
