name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Anything can be retagged if a fallback image exists (e.g. test)
  retag:
    permissions:
      packages: write
    name: Retag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          package: backend
          keep_versions: 10
          tag: ${{ github.event.number }}-retag
          tag_fallback: test
          triggers: ('backend/')

  # QuickStart apps build from the same dirs as their Dockerfiles
  basic:
    permissions:
      packages: write
    name: Basic
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          package: backend
          keep_versions: 10
          repository: bcgov/openshift-quickstart
          tag: ${{ github.event.number }}

  # FOM apps build from repo root, one above their Dockerfiles
  advanced:
    permissions:
      packages: write
    name: Advanced
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          package: api
          build_context: .
          build_file: api/Dockerfile
          keep_versions: 10
          repository: bcgov/nr-fom
          tag: ${{ github.event.number }}
